import {
    Clock,
    Sparkles
} from "lucide-react";
import React from "react";
import { difficultyColors } from "../utils/constants";
import StarRating from "./StarRating";

const RecipeCard = ({ recipe, theme, onSelect }) => {
  const isAiGenerated = recipe?.recipeType === "AI Generated";

  return (
    <div
      onClick={() => onSelect(recipe.id)}
      className={`${theme.cardBg} rounded-lg ${theme.shadow} overflow-hidden border ${theme.border} cursor-pointer transition-all duration-300 hover:shadow-xl hover:-translate-y-1 flex flex-col`}
      role="button"
      tabIndex={0}
      onKeyPress={(e) => (e.key === "Enter" || e.key === " ") && onSelect(recipe.id)}
    >
      <div className="relative">
        <img
          src={recipe.image || "/ai-card.png"}
          alt={recipe.title}
          className="w-full h-48 object-cover border-b ${theme.border}"
          loading="lazy"
        />
        {isAiGenerated && (
          <div
            className={`absolute top-0 right-0 flex items-center text-xs p-2 m-2 rounded-md ${difficultyColors.AI}
              `}
            title="This recipe was generated by AI"
          >
            <Sparkles size={14} className="mr-1 flex-shrink-0" /> AI Generated
          </div>
        )}
      </div>
      <div className="p-4 flex flex-col flex-grow">
        <div className="flex justify-between items-start mb-1 gap-2">
          <h3
            className="text-lg font-semibold mb-1 line-clamp-1 flex-grow mr-1"
            title={recipe.title}
          >
            {recipe.title}
          </h3>
          <span
            className={`text-[10px] px-1.5 py-0.5 rounded font-medium whitespace-nowrap flex-shrink-0 ${
              difficultyColors[recipe.difficulty] || theme.tagBg
            }`}
          >
            {recipe.difficulty}
          </span>
        </div>
        <p className={`${theme.subText} text-sm mb-3 h-10 line-clamp-2`}>{recipe.description}</p>
        <div className="flex flex-wrap gap-1.5 mb-3 min-h-[24px]">
          {recipe.tags.slice(0, 3).map((tag) => (
            <span
              key={tag}
              className={`text-[10px] px-2 py-0.5 rounded-full ${theme.tagBg} ${theme.tagText} border ${theme.border}`}
            >
              {tag}
            </span>
          ))}
        </div>
        <div className="flex justify-between items-center mt-auto pt-2 border-t ${theme.border} text-xs ${theme.subText}">
          <div className="flex items-center" title="Total Time">
            <Clock size={14} className="mr-1" />
            {recipe.totalTime}
          </div>
          <StarRating rating={recipe.rating} theme={theme} />
        </div>
      </div>
    </div>
  );
};

export default React.memo(RecipeCard);
