export const difficultyColors = {
  Easy: "bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-400 border border-green-300 dark:border-green-700",
  Medium:
    "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/50 dark:text-yellow-400 border border-yellow-300 dark:border-yellow-700",
  Hard: "bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-400 border border-red-300 dark:border-red-700",
  AI: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-100 border border-blue-300 dark:border-blue-700",
};

export const initialMockRecipes = [
  {
    id: 1,
    title: "Classic Tomato Soup",
    description: "A creamy and comforting tomato soup, perfect for a chilly day.",
    image: "/tomato-soup.jpg",
    prepTime: "10 min",
    cookTime: "20 min",
    totalTime: "30 min",
    servings: 4,
    rating: 4.5,
    difficulty: "Easy",
    tags: ["Vegetarian", "Soup", "Comfort Food", "Gluten-Free"],
    ingredients: [
      { quantity: 2, unit: "tbsp", name: "Olive oil" },
      { quantity: 1, unit: "", name: "Onion, chopped" },
      { quantity: 2, unit: "cloves", name: "Garlic, minced" },
      { quantity: 800, unit: "g", name: "Canned crushed tomatoes" },
      { quantity: 4, unit: "cups", name: "Vegetable broth" },
      { quantity: 0.5, unit: "cup", name: "Heavy cream (optional)" },
      { quantity: 1, unit: "tsp", name: "Dried basil" },
      { quantity: 0, unit: "", name: "Salt and pepper to taste" },
    ],
    instructions: [
      { text: "Heat olive oil in a large pot or Dutch oven over medium heat.", estimatedTime: 30 },
      { text: "Add chopped onion and cook until softened, about 5 minutes.", estimatedTime: 300 },
      {
        text: "Stir in minced garlic and cook for another minute until fragrant.",
        estimatedTime: 60,
      },
      {
        text: "Pour in the crushed tomatoes and vegetable broth. Add dried basil.",
        estimatedTime: 45,
      },
      {
        text: "Bring the soup to a simmer, then reduce heat and let it cook for 10-15 minutes, stirring occasionally.",
        estimatedTime: 720,
      },
      {
        text: "Carefully use an immersion blender to blend the soup until smooth. Alternatively, let it cool slightly and blend in batches in a regular blender.",
        estimatedTime: 180,
      },
      { text: "Return the soup to the pot. If using, stir in the heavy cream.", estimatedTime: 30 },
      {
        text: "Season with salt and pepper to taste. Serve hot, garnished with fresh basil or croutons if desired.",
        estimatedTime: 60,
      },
    ],
  },
  {
    id: 2,
    title: "Simple Lemon Herb Roasted Chicken",
    description: "Juicy roasted chicken with bright lemon and fragrant herbs.",
    image: "/roast-chicken.avif",
    prepTime: "15 min",
    cookTime: "1 hr 15 min",
    totalTime: "1 hr 30 min",
    servings: 4,
    rating: 4.8,
    difficulty: "Medium",
    tags: ["Chicken", "Roast", "Main Course", "Dinner"],
    ingredients: [
      { quantity: 1, unit: "(~1.5kg)", name: "Whole chicken" },
      { quantity: 1, unit: "", name: "Lemon, halved" },
      { quantity: 4, unit: "sprigs", name: "Fresh rosemary" },
      { quantity: 4, unit: "sprigs", name: "Fresh thyme" },
      { quantity: 3, unit: "tbsp", name: "Olive oil" },
      { quantity: 4, unit: "cloves", name: "Garlic, smashed" },
      { quantity: 0, unit: "", name: "Salt and freshly ground black pepper" },
    ],
    instructions: [
      { text: "Preheat oven to 200°C (400°F).", estimatedTime: 120 },
      {
        text: "Pat the chicken dry with paper towels. This helps the skin crisp up.",
        estimatedTime: 60,
      },
      {
        text: "Place the chicken in a roasting pan or large oven-safe skillet.",
        estimatedTime: 30,
      },
      {
        text: "Squeeze the juice of one lemon half over the chicken. Place both lemon halves, rosemary sprigs, thyme sprigs, and smashed garlic cloves inside the cavity of the chicken.",
        estimatedTime: 120,
      },
      {
        text: "Drizzle the chicken with olive oil. Season generously inside and out with salt and pepper.",
        estimatedTime: 60,
      },
      {
        text: "Roast for 1 hour and 15-20 minutes, or until the juices run clear when pierced with a fork or a thermometer inserted into the thickest part of the thigh reads 75°C (165°F).",
        estimatedTime: 4500,
      },
      { text: "Let the chicken rest for 10-15 minutes before carving.", estimatedTime: 600 },
      { text: "Serve with roasted vegetables or your favorite side dish.", estimatedTime: 30 },
    ],
  },
  {
    id: 3,
    title: "Quick Chickpea Salad Sandwich",
    description: "A fast, flavorful, and vegetarian alternative to tuna salad.",
    image: "/chickpea-salad.jpg",
    prepTime: "15 min",
    cookTime: "0 min",
    totalTime: "15 min",
    servings: 2,
    rating: 4.2,
    difficulty: "Easy",
    tags: ["Vegetarian", "Sandwich", "Lunch", "Quick", "Vegan Option"],
    ingredients: [
      { quantity: 1, unit: "(400g) can", name: "Chickpeas, rinsed and drained" },
      { quantity: 0.25, unit: "cup", name: "Mayonnaise (or vegan mayo)" },
      { quantity: 2, unit: "tbsp", name: "Red onion, finely chopped" },
      { quantity: 1, unit: "stalk", name: "Celery, finely chopped" },
      { quantity: 1, unit: "tbsp", name: "Fresh dill, chopped" },
      { quantity: 1, unit: "tsp", name: "Dijon mustard" },
      { quantity: 1, unit: "tbsp", name: "Lemon juice" },
      { quantity: 0, unit: "", name: "Salt and pepper to taste" },
      { quantity: 4, unit: "slices", name: "Bread or rolls" },
      { quantity: 0, unit: "", name: "Lettuce, tomato slices (for serving)" },
    ],
    instructions: [
      {
        text: "In a medium bowl, mash the chickpeas with a fork or potato masher until mostly broken down but still slightly chunky.",
        estimatedTime: 180,
      },
      {
        text: "Add the mayonnaise, red onion, celery, dill, Dijon mustard, and lemon juice to the bowl.",
        estimatedTime: 60,
      },
      { text: "Stir everything together until well combined.", estimatedTime: 60 },
      { text: "Season with salt and pepper to taste.", estimatedTime: 30 },
      {
        text: "Serve the chickpea salad on bread or rolls with lettuce and tomato slices.",
        estimatedTime: 120,
      },
    ],
  },
  {
    id: 4,
    title: "Authentic Pasta Carbonara",
    description:
      "A classic Roman pasta dish made with eggs, Pecorino Romano, guanciale, and black pepper.",
    image: "/carbonara.jpg",
    prepTime: "10 min",
    cookTime: "15 min",
    totalTime: "25 min",
    servings: 2,
    rating: 4.9,
    difficulty: "Medium",
    tags: ["Pasta", "Italian", "Dinner", "Classic"],
    ingredients: [
      { quantity: 200, unit: "g", name: "Spaghetti or Bucatini" },
      { quantity: 100, unit: "g", name: "Guanciale (or Pancetta), diced" },
      { quantity: 2, unit: "", name: "Large eggs" },
      { quantity: 1, unit: "", name: "Large egg yolk" },
      { quantity: 50, unit: "g", name: "Pecorino Romano cheese, finely grated" },
      { quantity: 0, unit: "", name: "Freshly cracked black pepper" },
      { quantity: 0, unit: "", name: "Salt (for pasta water)" },
    ],
    instructions: [
      {
        text: "Bring a large pot of salted water to a boil. Add pasta and cook according to package directions until al dente.",
        estimatedTime: 600,
      },
      {
        text: "While pasta cooks, heat a large skillet over medium heat. Add guanciale and cook until crispy and fat has rendered, about 5-7 minutes. Remove guanciale with a slotted spoon and set aside, leaving the rendered fat in the skillet.",
        estimatedTime: 420,
      },
      {
        text: "In a medium bowl, whisk together the whole eggs, egg yolk, and grated Pecorino Romano cheese. Season generously with black pepper.",
        estimatedTime: 60,
      },
      {
        text: "When pasta is cooked, reserve about 1/2 cup of pasta water, then drain the pasta.",
        estimatedTime: 30,
      },
      {
        text: "Add the drained pasta directly to the skillet with the rendered guanciale fat. Toss well to coat. Remove skillet from heat.",
        estimatedTime: 30,
      },
      {
        text: "Quickly pour the egg and cheese mixture over the hot pasta, tossing rapidly to combine. The heat of the pasta will cook the eggs and create a creamy sauce. If the sauce seems too thick, add a tablespoon or two of the reserved pasta water until desired consistency is reached.",
        estimatedTime: 90,
      },
      { text: "Stir in the crispy guanciale.", estimatedTime: 15 },
      {
        text: "Serve immediately, garnished with more grated Pecorino Romano and black pepper.",
        estimatedTime: 30,
      },
    ],
  },
  {
    id: 5,
    title: "Molten Chocolate Lava Cakes",
    description: "Decadent individual chocolate cakes with a gooey, melted chocolate center.",
    image: "/lava-cake.jpg",
    prepTime: "15 min",
    cookTime: "12-14 min",
    totalTime: "29 min",
    servings: 4,
    rating: 4.7,
    difficulty: "Medium",
    tags: ["Dessert", "Chocolate", "Baking", "Indulgent"],
    ingredients: [
      { quantity: 115, unit: "g", name: "Bittersweet chocolate (60-70%), chopped" },
      { quantity: 115, unit: "g", name: "Unsalted butter, cubed" },
      { quantity: 2, unit: "", name: "Large eggs" },
      { quantity: 2, unit: "", name: "Large egg yolks" },
      { quantity: 0.25, unit: "cup", name: "Granulated sugar" },
      { quantity: 0.5, unit: "tsp", name: "Vanilla extract" },
      { quantity: 2, unit: "tbsp", name: "All-purpose flour" },
      { quantity: 0, unit: "", name: "Pinch of salt" },
      { quantity: 0, unit: "", name: "Cocoa powder and butter, for ramekins" },
    ],
    instructions: [
      {
        text: "Preheat oven to 220°C (425°F). Generously butter four 6-ounce ramekins. Dust with cocoa powder, tapping out the excess.",
        estimatedTime: 180,
      },
      {
        text: "In a medium microwave-safe bowl, combine chopped chocolate and cubed butter. Microwave in 30-second intervals, stirring after each, until melted and smooth.",
        estimatedTime: 120,
      },
      {
        text: "In a separate large bowl, whisk together eggs, egg yolks, granulated sugar, and vanilla extract until pale and slightly thickened, about 2 minutes.",
        estimatedTime: 120,
      },
      {
        text: "Gently fold the melted chocolate mixture into the egg mixture until just combined.",
        estimatedTime: 60,
      },
      {
        text: "In a small bowl, whisk together flour and salt. Fold the flour mixture into the chocolate batter until no streaks remain.",
        estimatedTime: 60,
      },
      { text: "Divide the batter evenly among the prepared ramekins.", estimatedTime: 60 },
      {
        text: "Place ramekins on a baking sheet. Bake for 12-14 minutes, until the edges are set but the center is still soft and slightly jiggly.",
        estimatedTime: 780,
      },
      { text: "Let the cakes cool in the ramekins for 1-2 minutes.", estimatedTime: 90 },
      {
        text: "To serve, carefully run a thin knife around the edge of each cake, then invert onto serving plates. Garnish with powdered sugar, berries, or ice cream if desired. Serve immediately.",
        estimatedTime: 60,
      },
    ],
  },
  {
    id: 6,
    title: "Refreshing Mango Lassi",
    description: "A popular, creamy, and refreshing Indian yogurt-based drink.",
    image: "/mango-lassi.webp",
    prepTime: "5 min",
    cookTime: "0 min",
    totalTime: "5 min",
    servings: 2,
    rating: 4.6,
    difficulty: "Easy",
    tags: ["Drink", "Indian", "Yogurt", "Mango", "Vegetarian", "Quick", "Gluten-Free"],
    ingredients: [
      { quantity: 1, unit: "cup", name: "Plain yogurt (full fat recommended)" },
      { quantity: 0.5, unit: "cup", name: "Milk" },
      { quantity: 1, unit: "cup", name: "Chopped ripe mango (fresh or frozen)" },
      { quantity: 2, unit: "tbsp", name: "Sugar or honey (optional, to taste)" },
      { quantity: 0.25, unit: "tsp", name: "Cardamom powder (optional)" },
      { quantity: 0, unit: "", name: "Ice cubes (optional)" },
    ],
    instructions: [
      {
        text: "Combine yogurt, milk, chopped mango, sugar/honey (if using), and cardamom powder (if using) in a blender.",
        estimatedTime: 60,
      },
      { text: "Blend until smooth and creamy.", estimatedTime: 60 },
      {
        text: "If the lassi is too thick, add a little more milk. If it's too thin, add a few more mango pieces or ice cubes.",
        estimatedTime: 30,
      },
      { text: "Taste and adjust sweetness if necessary.", estimatedTime: 30 },
      {
        text: "Pour into glasses and serve immediately. Garnish with a mint sprig or a pinch of cardamom if desired.",
        estimatedTime: 30,
      },
    ],
  },
  {
    id: 7,
    title: "Mediterranean Quinoa Salad",
    description:
      "A healthy and vibrant salad packed with fresh vegetables, feta, and a lemon vinaigrette.",
    image: "/quinoa-salad.webp",
    prepTime: "20 min",
    cookTime: "15 min",
    totalTime: "35 min",
    servings: 4,
    rating: 4.4,
    difficulty: "Easy",
    tags: ["Salad", "Vegetarian", "Healthy", "Lunch", "Gluten-Free", "Mediterranean"],
    ingredients: [
      { quantity: 1, unit: "cup", name: "Quinoa, rinsed" },
      { quantity: 2, unit: "cups", name: "Water or vegetable broth" },
      { quantity: 1, unit: "", name: "Cucumber, diced" },
      { quantity: 1, unit: "cup", name: "Cherry tomatoes, halved" },
      { quantity: 0.5, unit: "", name: "Red onion, finely chopped" },
      { quantity: 0.5, unit: "cup", name: "Kalamata olives, pitted and halved" },
      { quantity: 0.5, unit: "cup", name: "Feta cheese, crumbled" },
      { quantity: 0.25, unit: "cup", name: "Fresh parsley, chopped" },
      // Dressing
      { quantity: 3, unit: "tbsp", name: "Olive oil" },
      { quantity: 2, unit: "tbsp", name: "Lemon juice" },
      { quantity: 1, unit: "tsp", name: "Dried oregano" },
      { quantity: 0, unit: "", name: "Salt and pepper to taste" },
    ],
    instructions: [
      {
        text: "Cook the quinoa: In a medium saucepan, combine rinsed quinoa and water/broth. Bring to a boil, then reduce heat, cover, and simmer for 15 minutes, or until liquid is absorbed.",
        estimatedTime: 960,
      },
      {
        text: "Remove quinoa from heat and let it sit covered for 5 minutes. Fluff with a fork and let it cool completely.",
        estimatedTime: 300,
      },
      {
        text: "Prepare the dressing: In a small bowl, whisk together olive oil, lemon juice, dried oregano, salt, and pepper.",
        estimatedTime: 60,
      },
      {
        text: "Assemble the salad: In a large bowl, combine the cooled quinoa, diced cucumber, cherry tomatoes, red onion, Kalamata olives, crumbled feta cheese, and chopped parsley.",
        estimatedTime: 180,
      },
      { text: "Pour the dressing over the salad and toss gently to combine.", estimatedTime: 30 },
      {
        text: "Taste and adjust seasoning if needed. Serve immediately or chilled.",
        estimatedTime: 30,
      },
    ],
  },
];
